// English labels for the entire app
export const en = {
  // Navigation
  nav: {
    dashboard: "Dashboard",
    projects: "Projects",
    clients: "Clients",
    equipment: "Equipment",
    financials: "Financials",
    calendar: "Content Calendar",
    contacts: "Contacts",
    subscriptions: "Subscriptions",
    travelLog: "Travel Log",
    assets: "Licenses",
    inspiration: "Inspiration",
    cheatSheets: "Guides",
    scripts: "Scripts",
    moodboard: "Moodboard",
    billing: "Billing",
  },

  // Dashboard
  dashboard: {
    title: "Dashboard",
    activeProjects: "Active Projects",
    upcomingShoots: "Upcoming Events",
    pendingDeadlines: "Pending Deadlines",
    monthlyRevenue: "Monthly Revenue",
    outstandingInvoices: "Outstanding Invoices",
    conversionRate: "Conversion Rate",
    recentProjects: "Recent Projects",
    recentClients: "Recent Clients",
    noProjects: "No active projects",
    noShoots: "No upcoming events",
  },

  // Projects
  project: {
    title: "Projects",
    newProject: "New Project",
    phases: {
      // Legacy
      pre_production:    "Pre-Production",
      production:        "Production",
      post_production:   "Post-Production",
      delivered:         "Delivered",
      revisions:         "Revisions",
      // Photography
      coordination:      "Coordination",
      shoot_day:         "Shoot Day",
      shoot_days:        "Shoot Days",
      selection:         "Selection",
      editing:           "Editing",
      gallery_delivery:  "Gallery Delivery",
      // Video / Content
      brief:             "Brief",
      planning:          "Planning",
      monthly_planning:  "Monthly Planning",
      research:          "Research",
      recording:         "Recording",
      writing:           "Writing",
      graphics:          "Graphics",
      waiting_approval:  "Waiting for Approval",
      published:         "Published",
      scheduling:        "Scheduling",
      active:            "Active",
      // Editing
      materials_received: "Materials Received",
      first_cut:          "First Cut",
      draft:              "Draft",
    },
    statuses: {
      pitching:       "Pitching",
      scripting:      "Scripting",
      moodboards:     "Moodboarding",
      location_scouting: "Location Scouting",
      scheduled:      "Scheduled",
      shooting:       "Shooting",
      wrapping:       "Wrapping Up",
      ingest_sync:    "Ingesting",
      rough_cut:      "Rough Cut",
      revisions_v1:   "Revision 1",
      revisions_v2:   "Revision 2",
      color_sound:    "Color & Sound",
      final_delivery: "Final Delivery",
      delivered:      "Delivered",
      archived:       "Archived",
    },
    types: {
      // Legacy
      youtube:     "YouTube Video",
      music_video: "Music Video",
      commercial:  "Commercial",
      corporate:   "Corporate",
      social:      "Social Media",
      // Photography
      wedding:             "Wedding",
      bar_bat_mitzva:      "Bar / Bat Mitzvah",
      event_photo:         "Event",
      portrait:            "Portrait / Mini Session",
      product_photography: "Product Photography",
      real_estate:         "Real Estate",
      fashion:             "Fashion",
      family:              "Family / Maternity",
      // Video
      podcast:   "Podcast",
      interview: "Interview",
      bts:       "BTS",
      // Content
      reel:             "Reel / Story",
      post_carousel:    "Post / Carousel",
      page_management:  "Page Management (Retainer)",
      content_strategy: "Content Strategy",
      // Editing
      video_editing:   "Video Editing",
      podcast_editing: "Podcast Editing",
      motion_graphics: "Motion Graphics",
    },
    shootDate: "Date",
    deadline:  "Deadline",
    budget:    "Budget",
    client:    "Client",
    description: "Description",
    type: "Project Type",
  },

  // Clients
  client: {
    title: "Clients",
    newClient: "New Client",
    newLead: "New Lead",
    name: "Name",
    email: "Email",
    phone: "Phone",
    company: "Company",
    notes: "Notes",
    type: "Type",
    types: {
      lead: "Lead",
      client: "Client",
    },
    leadSource: "Lead Source",
    leadSources: {
      linkedin: "LinkedIn",
      organic: "Organic",
      referral: "Referral",
      website: "Website",
      social: "Social Media",
      other: "Other",
    },
    leadStatus: "Lead Status",
    leadStatuses: {
      new: "New",
      contacted: "Contacted",
      qualified: "Qualified",
      proposal_sent: "Proposal Sent",
      won: "Won",
      lost: "Lost",
    },
    interactions: "Interaction History",
    interactionTypes: {
      call: "Call",
      email: "Email",
      meeting: "Meeting",
      note: "Note",
    },
  },

  // Equipment
  equipment: {
    title: "Equipment",
    newItem: "New Item",
    name: "Name",
    category: "Category",
    brand: "Brand",
    model: "Model",
    serialNumber: "Serial Number",
    purchasePrice: "Purchase Price",
    status: "Status",
    categories: {
      camera: "Camera",
      lens: "Lens",
      drone: "Drone",
      lighting: "Lighting",
      audio: "Audio",
      grip: "Grip",
      other: "Other",
    },
    statuses: {
      available: "Available",
      rented: "Rented",
      in_repair: "In Repair",
      retired: "Retired",
    },
  },

  // Financials
  financial: {
    title: "Financials",
    quotes: "Quotes",
    invoices: "Invoices",
    expenses: "Expenses",
    newQuote: "New Quote",
    newInvoice: "New Invoice",
    newExpense: "New Expense",
    subtotal: "Subtotal",
    tax: "VAT (17%)",
    total: "Total",
    status: "Status",
    quoteStatuses: {
      draft: "Draft",
      sent: "Sent",
      accepted: "Accepted",
      declined: "Declined",
    },
    invoiceStatuses: {
      draft: "Draft",
      sent: "Sent",
      paid: "Paid",
      overdue: "Overdue",
      cancelled: "Cancelled",
    },
    expenseCategories: {
      overhead: "Overhead",
      project: "Project Expense",
      gear_purchase: "Gear Purchase",
      vehicle_travel: "Vehicle / Travel",
      other: "Other",
    },
  },

  // Content Calendar
  calendar: {
    title: "Content Calendar",
    newContent: "New Content",
    contentTypes: {
      client_shoot: "Client Shoot",
      youtube_long: "YouTube Long",
      short_form: "Short Form",
    },
    statuses: {
      planned: "Planned",
      editing: "Editing",
      ready: "Ready to Publish",
      published: "Published",
    },
    noContent: "No content planned",
    upcomingContent: "Upcoming Content & Shoots",
    dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    selectEvent: "Select event to add to Google Calendar",
    noEventsInView: "No events in current view",
    newShort: "New",
  },

  // Contacts / Crew Rolodex
  contacts: {
    title: "Contacts",
    newContact: "New Contact",
    categories: {
      editor: "Editor",
      stills_photographer: "Stills Photographer",
      video_photographer: "Video Photographer",
      lighting: "Lighting",
      director: "Director",
      art: "Art",
      production_assistant: "Production Assistant",
      producer: "Producer",
      three_d: "3D",
      sound_designer: "Sound Designer",
      makeup: "Makeup",
      actor: "Actor",
      rental_house: "Rental House",
      studio: "Studio",
      social_manager: "Social Manager",
    },
  },

  // Subscriptions
  subscriptions: {
    title: "Monthly Subscriptions",
    newSubscription: "New Subscription",
    totalMonthly: "Total Monthly Cost",
    cycles: {
      monthly: "Monthly",
      yearly: "Yearly",
    },
    statuses: {
      active: "Active",
      cancelled: "Cancelled",
    },
  },

  // Travel Log
  travelLog: {
    title: "Travel Log",
    newEntry: "New Trip",
    totalKm: "Total km this month",
    origin: "Origin",
    destination: "Destination",
    kilometers: "km",
  },

  // Asset Library
  assets: {
    title: "Licenses",
    newAsset: "New Asset",
    types: {
      music: "Music",
      sfx: "Sound Effects",
      font: "Font",
      stock_footage: "Stock Footage",
    },
  },

  // Inspiration Board
  inspiration: {
    title: "Inspiration Board",
    newItem: "New Inspiration",
    categories: {
      lighting: "Lighting",
      editing: "Editing",
      hooks: "Hooks",
      thumbnails: "Thumbnails",
    },
  },

  // Cheat Sheets
  cheatSheets: {
    title: "Guides & SOPs",
    newSheet: "New Guide",
  },

  // Scripts
  scripts: {
    title: "Scripts",
    newScript: "New Script",
    untitled: "Untitled Script",
    editor: {
      placeholder: "Start writing your script...",
      saving: "Saving...",
      saved: "Saved",
      unsaved: "Unsaved",
    },
    ai: {
      title: "AI Copilot",
      generateTab: "Generate",
      upgradeTab: "Upgrade",
      instructTab: "Instructions",
      generatePlaceholder: "Describe the script you want (topic, length, platform)...",
      instructPlaceholder: "Tell the AI what to change...",
      generateButton: "Generate Script",
      upgradeButton: "Upgrade Script",
      applyButton: "Apply",
      generating: "Generating...",
      upgrading: "Upgrading...",
      applying: "Applying...",
    },
    noScripts: "No scripts yet",
    deleteConfirm: "Delete this script?",
  },

  // Dashboard Widgets
  widgets: {
    quickNotes: "Quick Notes",
    quickNotesPlaceholder: "Write ideas here...",
    todos: "Daily Tasks",
    todosPlaceholder: "Add a task...",
    quickLinks: "Quick Links",
    newLink: "New Link",
    gearReset: "Gear Status",
    gearItems: {
      sd_cards: "SD Cards",
      footage: "Footage Backup",
      batteries: "Batteries",
    },
    gearReady: "Ready",
    gearNotReady: "Needs Attention",
  },

  // Common
  common: {
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    delete: "Delete",
    deleting: "Deleting...",
    edit: "Edit",
    add: "Add",
    search: "Search",
    searchPlaceholder: "Search...",
    filter: "Filter",
    noResults: "No results found",
    loading: "Loading...",
    currency: "₪",
    signOut: "Sign Out",
    billingPlan: "Subscription Plan",
    back: "Back",
    close: "Close",
    confirm: "Confirm",
    name: "Name",
    email: "Email",
    phone: "Phone",
    notes: "Notes",
    date: "Date",
    status: "Status",
    actions: "Actions",
    active: "Active",
    inactive: "Inactive",
    all: "All",
    none: "None",
    optional: "Optional",
    required: "Required",
    new: "New",
    update: "Update",
    create: "Create",
    description: "Description",
    title: "Title",
    category: "Category",
    project: "Project",
    client: "Client",
    selectClient: "Select Client",
    selectProject: "Select Project",
    noClient: "No Client",
    noProject: "No Project",
    addNewClient: "Add New Client",
    newClientName: "New client name...",
    deleteConfirmTitle: "Confirm Deletion",
    deleteConfirmText: "Are you sure? This action cannot be undone.",
    addSocialNetwork: "Add Social Network",
    activeClient: "Active Client",
    editClient: "Edit Client",
    newClientTitle: "New Client",
    editContact: "Edit Contact",
    newContactTitle: "New Contact",
    editProject: "Edit Project",
    newProjectTitle: "New Project",
    enterProjectDetails: "Enter new project details",
    editProjectDetails: "Edit project details",
    projectName: "Project Name",
    createProject: "Create Project",
    addTask: "Add task...",
    removeFromProject: "Remove from Project",
    backToProjects: "Back to Projects",
    noTasks: "No tasks",
    noScriptsLinked: "No scripts",
    noMoodboardsLinked: "No Moodboards",
    noContactsLinked: "No contacts",
    noCalendarLinked: "No content planned",
    allLinked: "Everything is already linked",
    allClients: "All Clients",
    allCategories: "All Categories",
    perDay: "/ day",
    budget: "Budget",
    deadline: "Deadline",
    company: "Company",
    website: "Website",
    color: "Color",
    export: "Export",
    addToGCal: "Add to Google Calendar",
    events: "Events",
    activeClients: "Active Clients",
    totalClients: "Total Clients",
    noProjects: "No projects",
    noContent: "No content",
    linkToProject: "Link to Project",
    feedback: "Feedback",
    sendFeedback: "Send Feedback",
    sending: "Sending...",
    ratingOptional: "Rating (optional)",
    feedbackQuestion: "What do you think? What's missing? What worked great?",
    writeHere: "Write here...",
    thankYouFeedback: "Thank you for the feedback!",
    helpsUsImprove: "This helps us improve",
    sendAnother: "Send another",
    editContent: "Edit Content",
    newContentTitle: "New Content",
    editContentDetails: "Edit content details",
    enterContentDetails: "Add new content to the board",
    updateContent: "Update Content",
    addContent: "Add Content",
    deleteContent: "Delete",
    dailyRate: "Daily Rate",
    addNewCategory: "Add new category",
    newCategoryName: "New category name...",
    accountSettings: "Account Settings",
    billingPayments: "Billing & Payments",
    signOutAction: "Sign Out",
    editClientForm: "Edit client form",
    newClientForm: "Create new client form",
    editContactDetails: "Edit contact details",
    newContactDetails: "Add a new contact to the network",
    deleteTask: "Delete task",
    tasks: "Tasks",
    statusPlanning: "Planning",
    statusInProgress: "In Progress",
    statusReview: "Awaiting Approval",
    statusDone: "Completed",
    days: "days",
    assignedToProject: "Assigned to Project",
    noProjectsYet: "No projects yet",
    clickNewProject: "Click \"New Project\" to get started",
    tasksLabel: "Tasks",
  },

  // Auth
  auth: {
    welcomeBack: "Welcome back to Planify",
    signInSubtitle: "Sign in to your account to continue",
    email: "Email",
    password: "Password",
    signInButton: "Sign In",
    signingIn: "Signing in...",
    orContinueWith: "or continue with",
    noAccount: "Don't have an account?",
    freeSignUp: "Sign up free",
    invalidCredentials: "Invalid email or password",
    createAccount: "Create a Planify account",
    createAccountSubtitle: "The management system for photographers and producers",
    fullName: "Full Name",
    createAccountButton: "Create Free Account",
    creatingAccount: "Creating account...",
    agreeToTerms: "By signing up you agree to the Terms of Service and Privacy Policy",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign In",
    signUpFailed: "Something went wrong. Try again.",
    signUpSuccessSignInFailed: "Registration succeeded but sign-in failed. Try signing in manually.",
    minChars: "At least 6 characters",
  },

  // Profile / Settings
  profile: {
    accountSettings: "Account Settings",
    userDetails: "Your user details",
    fullName: "Full Name",
    notSet: "Not set",
    emailAddress: "Email Address",
    security: "Security",
    securityDesc: "Encrypted password · Login verification",
    languageLabel: "Language",
    changePassword: "Change Password",
    changePasswordDesc: "Choose a strong password of at least 6 characters",
    currentPassword: "Current Password",
    currentPasswordPlaceholder: "Enter current password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    confirmNewPasswordPlaceholder: "Repeat the new password",
    savePassword: "Save Password",
    passwordChanged: "Password changed successfully",
    passwordsDoNotMatch: "New passwords do not match",
    passwordTooShort: "New password must be at least 6 characters",
    passwordChangeError: "Error changing password",
    networkError: "Network error, try again",
  },

  // Billing
  billing: {
    transparentPricing: "Transparent & flexible pricing",
    allIncluded: "Everything included. No surprises.",
    cancelAnytime: "Cancel anytime — no contracts, no penalties.",
    monthly: "Monthly",
    annual: "Annual",
    savings: "Save ₪118",
    freePlan: "Planify Free",
    trialDays: "3-day trial",
    forTrialDays: "For 3 trial days",
    currentPlan: "Current Plan",
    freeFeature1: "1 first project",
    freeFeature2: "3 clients",
    freeFeature3: "Full access for 3 days",
    freeFeature4: "No credit card",
    proAnnual: "Planify Pro Annual",
    proMonthly: "Planify Pro Monthly",
    annualBilling: "Annual billing",
    monthlyBilling: "Monthly billing, cancel anytime",
    perMonth: "/ month",
    annualPriceSuffix: "/ month — billed ₪590/year",
    monthlyPriceSuffix: "/ month — billed monthly",
    twoMonthsFree: "✓ Two months free vs monthly",
    startNow: "Start Now",
    bestValue: "✦ Best Value",
    proFeature1: "Unlimited projects",
    proFeature2: "Unlimited clients & contacts",
    proFeature3: "All system features",
    proFeature4: "Invoices & quotes",
    proFeature5: "Content calendar + scripts",
    proFeature6: "Inspiration board & moodboard",
    proFeatureAnnual1: "Priority support",
    proFeatureAnnual2: "Two months free",
    fullComparison: "Full Comparison",
    feature: "Feature",
    unlimited: "Unlimited",
    trustCancel: "Cancel anytime",
    trustCancelDesc: "No contracts, no penalties.",
    trustUpgrade: "Instant upgrade",
    trustUpgradeDesc: "Switch to a higher plan with one click.",
    trustData: "Your data",
    trustDataDesc: "All data is kept even after cancellation.",
    manageSubscription: "To manage your current subscription",
    clickHere: "click here ←",
    trialExpiredTitle: "Your trial has expired",
    trialExpiredDesc: "The 3 days have passed. Choose a plan to continue using the system.",
    featureProjects: "Projects",
    featureClients: "Clients",
    featureContacts: "Contacts",
    featureDocuments: "Documents to upload",
    featureScripts: "Scripts",
    featureInspiration: "Inspiration boards (items)",
    featureMoodboards: "Moodboards",
    featureDailyTasks: "Daily tasks",
    featureInvoices: "Invoices & quotes",
    featureCalendar: "Content calendar",
    featureExpenses: "Expense management",
    featurePrioritySupport: "Priority support",
    goBack: "Back",
    completePurchase: "Complete Purchase",
    cardNumber: "Card Number",
    cardholderName: "Cardholder Name",
    expiryDate: "Expiry Date",
    creditCardDetails: "Credit Card Details",
    secureSSL: "Secure SSL payment",
    pciEncryption: "PCI DSS encryption",
    cancelAnytimeNoCharge: "Cancel anytime, no extra charge",
    processingPayment: "Processing payment...",
    payNow: "Pay",
    now: "now",
    agreeTerms: "By clicking \"Pay\" you agree to the",
    termsOfService: "Terms of Service",
    and: "and",
    privacyPolicy: "Privacy Policy",
    invalidCardNumber: "Invalid card number",
    enterCardholderName: "Please enter cardholder name",
    invalidExpiry: "Invalid expiry date",
    invalidCVV: "Invalid CVV",
    paymentError: "Error processing payment",
    subscriptionAndPayments: "Billing & Payments",
    subscriptionManagement: "Manage your subscription, payment method, and billing options",
    welcomePro: "Welcome to the Pro plan!",
    upgradeSuccess: "Upgrade successful. You now have access to all features.",
    activePlan: "Active Plan",
    statusLabel: "Status",
    canceled: "Canceled",
    activeStatus: "Active",
    freeStatus: "Free",
    accessUntil: "Access until",
    nextRenewal: "Next renewal",
    planQuotas: "Plan quotas",
    projectsQuota: "Projects",
    contactsQuota: "Contacts",
    documentsQuota: "Documents",
    scriptsQuota: "Scripts",
    includedInPlan: "What's included in your plan",
    includedFeature1: "All system features",
    includedFeature2: "Invoices & quotes",
    includedFeature3: "Content calendar + scripts + inspiration",
    includedFeature4: "Access to all future updates",
    upgradeForMore: "Upgrade for larger quotas and access to all features",
    upgradeToPro: "Upgrade to Pro",
    paymentMethod: "Payment Method",
    comingSoon: "Coming soon",
    paymentMethodDesc: "Payment method management will be available after connecting the payment system (Stripe).",
    paymentMethodNote: "After connection — the button will open the Stripe customer portal for card management.",
    cancelSubscription: "Cancel Subscription",
    cancelDesc: "After cancellation you'll continue to have access until the end of the current billing period.",
    cancelConfirmTitle: "Cancel Subscription",
    cancelConfirmDesc: "Are you sure you want to cancel? You'll lose access to premium features at the end of the current billing cycle.",
    keepSubscription: "Keep my subscription",
    yesCancelSubscription: "Yes, cancel subscription",
    canceling: "Canceling...",
    canceledNotice: "Your subscription has been canceled. You can continue using premium features until",
    loadError: "Unable to load subscription details. Try refreshing the page.",
    refresh: "Refresh",
  },

  // Moodboard
  moodboard: {
    title: "Moodboard",
    subtitle: "Design and collect visual inspiration for your projects",
    newMoodboard: "New Moodboard",
    noMoodboards: "No Moodboards yet",
    noMoodboardsDesc: "Create a new Moodboard to start collecting inspiration",
    createFirst: "Create First Moodboard",
    updated: "Updated",
    deleteConfirm: "Delete this board?",
    writeHere: "Write here...",
    addDescription: "Add description...",
    editLink: "Edit link",
    linkDescription: "Link description",
    newNote: "New note",
    newHeading: "New heading",
    heading: "Heading",
    deleteNode: "Delete",
    imageAlt: "Image",
    linkTab: "Link",
    uploadTab: "Upload",
    cameraTab: "Camera",
    showImage: "Show image",
    clickToSelectImage: "Click to select image",
    openCamera: "Open camera",
    maxSize: "Max 8MB",
    addImage: "Add image",
    uploadFileNote: "Click to attach file (PDF, JPG, PNG)",
    uploading: "Uploading...",
    typeText: "Type text...",
    textColor: "Text",
    bgColor: "Background",
    noBg: "No background",
    defaultFont: "Default",
    rect: "Rectangle",
    circle: "Circle",
    triangle: "Triangle",
    diamond: "Diamond",
    star: "Star",
    arrow: "Arrow",
    contentBoards: "Content boards",
    pasteImageLink: "Paste image link...",
    descriptionOptional: "Description (optional)",
    titleOptional: "Title (optional)",
    headingPlaceholder: "Heading...",
    save: "Save",
    link: "Link",
    rotate: "Rotate",
    fillColor: "Fill color",
    fillLabel: "Fill",
    strokeColor: "Stroke color",
    strokeLabel: "Stroke",
    strokeWidth: "Width",
    color: "Color",
    clear: "Clear",
    rows: "Rows",
    columns: "Columns",
    stickyNote: "Sticky",
    image: "Image",
    text: "Text",
    table: "Table",
    shape: "Shape",
    draw: "Draw",
    pen: "Pen",
    eraser: "Eraser",
    finish: "Finish",
    back: "Back",
    saving: "Saving...",
    saved: "Saved",
    unsaved: "Unsaved",
    add: "Add",
    maxSizeAlert: "Max 8MB",
    maxSizeNote: "PNG, JPG, GIF, WEBP — up to 8MB",
    upgradeFeature: "Items on content board",
    drawingAlt: "Drawing",
    textColorTitle: "Text color",
    bgColorTitle: "Background color",
  },

  // Tasks page
  tasks: {
    title: "Tasks",
    activeCount: "active",
    doneCount: "completed",
    addNewTask: "Add a new task...",
    reachedLimit: "Reached limit of {limit} tasks — click to upgrade",
    allFilter: "All",
    activeFilter: "Active",
    doneFilter: "Completed",
    noDoneTasks: "No completed tasks yet",
    noTasksHere: "No tasks here",
    upgradeUnlimited: "Upgrade to Pro — unlimited tasks",
    freeLimit: "On the free plan:",
    dailyTasks: "Daily tasks",
    upgradeFeature1: "Unlimited projects & clients",
    upgradeFeature2: "Invoices & quotes",
    upgradeFeature3: "Inspiration board & scripts",
  },

  // Upgrade dialog
  upgrade: {
    reachedLimit: "You've reached the limit!",
    freeLimit: "On the free plan you can add up to",
    upgradeForUnlimited: "Upgrade to Pro for unlimited access.",
    feature1: "Unlimited projects, contacts & scripts",
    feature2: "Invoices, quotes & inspiration board",
    feature3: "Full access to all management tools",
    upgradeNow: "Upgrade to Pro Now",
    maybeLater: "Maybe later",
  },

  // Theme toggle
  theme: {
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
  },

  // Onboarding
  onboarding: {
    exit: "Exit",
    envReady: "Your environment is ready!",
    transferring: "Transferring you...",
    preparingEnv: "Preparing your environment...",
    oneSecond: "One second",
    whatDoYouDo: "What do you do?",
    selectMultiple: "You can select more than one option",
    mainGoal: "What is your main goal?",
    howDoYouWork: "How do you work?",
    selectTeamSize: "Select team size",
    finish: "Finish",
    continueBtn: "Continue",
    goBack: "→ Go back",
    roles: {
      videographer: "Videographer",
      videographerDesc: "Shooting, editing, delivering",
      photographer: "Stills Photographer",
      photographerDesc: "People & product photography",
      smm: "Social Media Manager",
      smmDesc: "Retainers & ongoing content",
      editor: "Video Editor",
      editorDesc: "Editing, graphics, animation",
      producer: "Producer",
      producerDesc: "Production & logistics management",
      agency: "Agency / Studio",
      agencyDesc: "Full team, multiple clients",
    },
    goals: {
      shoots_gear: "Shoot Management",
      shoots_gearDesc: "Schedules, logistics",
      retainer: "Ongoing Content",
      retainerDesc: "Retainers, monthly content",
      financials: "Invoices & Finances",
      financialsDesc: "Revenue, expenses, quotes",
      scripts: "Scripts & Creative",
      scriptsDesc: "Script writing, shot lists",
    },
    teamSizes: {
      solo: "Solo Freelancer",
      soloDesc: "Working alone mostly",
      small: "Small Team (2–5)",
      smallDesc: "Partner or a few employees",
      studio: "Studio (5+)",
      studioDesc: "Full team, organizational structure",
    },
  },

  // Admin
  admin: {
    dashboard: "Admin Dashboard",
    dashboardDesc: "User & subscription management",
    totalUsers: "Total Users",
    free: "Free",
    proMonthly: "Pro Monthly",
    proAnnual: "Pro Annual",
    mrr: "MRR",
    registeredThisWeek: "Registered this week",
    registeredThisMonth: "Registered this month",
    incompleteOnboarding: "Incomplete onboarding",
    totalProjects: "Total Projects",
    totalScripts: "Total Scripts",
    totalContacts: "Total Contacts",
    avgPerUser: "Average {avg} per user",
    searchPlaceholder: "Search by name or email...",
    user: "User",
    subscription: "Subscription",
    expiry: "Expiry",
    statusCol: "Status",
    joined: "Joined",
    changePlan: "Change Plan",
    actionsCol: "Actions",
    active: "Active",
    onboardingStatus: "Onboarding",
    resetPassword: "Reset Password",
    updateExpiry: "Update subscription expiry",
    deleteUser: "Delete user",
    deleteConfirm: "Delete",
    cancelAction: "Cancel",
    newPasswordPlaceholder: "New password...",
    updatePassword: "Update Password",
    expiryTitle: "Subscription Expiry",
    updateBtn: "Update",
    removeExpiry: "Remove expiry",
    passwordUpdated: "Password updated successfully",
    expiryUpdated: "Subscription expiry updated",
    noUsersFound: "No users found",
    feedbackTitle: "User Feedback",
    noFeedback: "No feedback yet",
    anonymous: "Anonymous",
    deleteFeedback: "Delete feedback",
  },

  // Welcome tour
  tour: {
    welcome: "Welcome to Planify!",
    welcomeDesc: "This is the CRM built especially for content creators, photographers, and producers. Let us show you what's here in a few seconds.",
    dashboardTitle: "Dashboard",
    dashboardDesc: "A quick overview of active projects, revenue, upcoming shoots, and open tasks — all in one place.",
    projectsTitle: "Projects",
    projectsDesc: "Track every project from the first inquiry to client delivery — organized by clear stages.",
    clientsTitle: "Clients",
    clientsDesc: "Manage leads, existing clients, and interactions. See at a glance who's ready to close and the status of every lead.",
    financialsTitle: "Financials",
    financialsDesc: "Send invoices and quotes, track expenses, and see your monthly profit in real-time.",
    calendarTitle: "Content Calendar",
    calendarDesc: "Plan posts, retainers, and shoots on a monthly calendar. See everything in a clear visual layout.",
    scriptsTitle: "Scripts",
    scriptsDesc: "Write and save scripts for videos, reels, and commercials. Everything organized by project and ready for production.",
    contactsTitle: "Contacts",
    contactsDesc: "Save phone numbers, emails, and contact details for photographers, editors, clients, and other collaborators.",
    inspirationTitle: "Inspiration Board",
    inspirationDesc: "Collect images, videos, and references by category. Fuel inspiration for upcoming projects and share with clients.",
    skip: "Skip",
    prev: "Previous",
    next: "Next",
    letsStart: "Let's Start",
    stepOf: "of",
  },

  // Calendar export
  calendarExport: {
    exportToClient: "Export to Client",
    allClients: "All Clients",
    layout: "Layout",
    grid: "Grid",
    list: "List",
    themeLabel: "Theme",
    light: "Light",
    dark: "Dark",
    darkModeNote: "Dark mode suits white logos",
    brandColor: "Brand Color",
    customColor: "Custom color",
    logo: "Logo",
    clickToUploadLogo: "Click to upload logo",
    removeLogo: "Remove logo",
    zoomLabel: "Zoom",
    exporting: "Exporting...",
    footerNote: "The logo, colors, and content are for client preview only",
    producedBy: "Produced by Planify",
    noContentThisMonth: "No content days this month",
    dateCol: "Date",
    productCol: "Product",
    platformCol: "Platform",
    exportPngFailed: "PNG export failed — try again",
    exportPdfFailed: "PDF export failed — try again",
    shoot: "Shoot",
  },

  // Script editor specific
  scriptEditor: {
    podcast: "Podcast",
    commercial: "Commercial",
    filterColumns: "Filter Columns",
    close: "Close",
    displayMode: "Display Mode",
    storyboard: "Story\nboard",
    textOnly: "Text\nOnly",
    cinematic: "Cinematic",
    foldRows: "Row Folding",
    open: "Open",
    folded: "Folded",
    customShotNo: "Custom Shot Numbers",
    customShotNoDesc: "Enable editing numbers as 1A, 2B",
    shotOrder: "Shot Order",
    ascending: "Ascending",
    descending: "Descending",
    addFrame: "Add",
    action: "Action...",
    lensPlaceholder: "Lens...",
    dialoguePlaceholder: "Dialogue...",
    notePlaceholder: "Note...",
    equipmentPlaceholder: "Equipment...",
    lightingPlaceholder: "Lighting...",
    actorPlaceholder: "Actor...",
    propPlaceholder: "Prop...",
    costumePlaceholder: "Costume...",
    makeupPlaceholder: "Makeup...",
    addImageStoryboard: "Add image",
    actionDesc: "Action / Description...",
    errorTryAgain: "Error. Try again.",
    deleteScript: "Delete this script?",
    createFirstScript: "Create First Script",
    createFirstScriptDesc: "Create a new script to get started",
    // Tabs
    tabScript: "Script",
    tabShotList: "Shot List",
    tabCallSheet: "Call Sheet",
    // Top bar
    scriptsBack: "Scripts",
    scriptTitlePlaceholder: "Script title...",
    customPlatformPlaceholder: "Custom platform...",
    linkedProject: "Project",
    noProject: "No project",
    assignToProject: "Link to project",
    saving: "Saving...",
    saved: "Saved",
    autoSave: "Auto-save",
    other: "Other...",
    // Script tab
    scriptPlaceholder: "Start writing your script...",
    addToShotList: "Add to Shot List",
    aiHelp: "AI Help",
    writingAssistant: "Writing Assistant",
    generateScript: "Generate Script",
    fromPrompt: "From prompt with AI",
    upgradeScript: "Upgrade Script",
    upgradeScriptDesc: "Hook, pacing & wording",
    aiPromptPlaceholder: "e.g. Video about a jewelry product, audience 25-35, aspirational tone",
    generate: "Generate",
    cancel: "Cancel",
    chatPlaceholder: "What to change? (Enter to send)",
    chatEmpty: "Tell the AI what to change in the script...",
    // Shot list tab
    shotListTitle: "Shot List",
    shotsCount: "shots",
    filter: "Filter",
    view: "View",
    addShot: "Shot",
    addShotFull: "Add Shot",
    addFirstShot: "Add First Shot",
    noShotsYet: "No shots yet",
    emptyShotListHint: "Click \"Add Shot\" to start building the shot list",
    moreShots: "More shots",
    shotLimit: "Limit of",
    shotLimitSuffix: "shots",
    upgradeToPro: "Upgrade to Pro",
    // Upgrade features
    cinematicFeature: "Cinematic view",
    callSheetFeature: "Call Sheet",
    storyboardShotsFeature: "Storyboard shots",
  },

  // Call sheet
  callSheet: {
    title: "Call Sheet",
    exporting: "Exporting...",
    exportPDF: "Export PDF",
    light: "Light",
    dark: "Dark",
    projectLabel: "Project:",
    clientLabel: "Client:",
    platformLabel: "Platform:",
    dateLabel: "Date",
    shotsCount: "shots",
    castSection: "Cast",
    lensSection: "Lenses",
    scheduleSection: "Shooting Schedule",
    noShotsAdded: "No shots added to the shot list",
    sceneName: "Scene Name",
    movement: "Movement",
    lens: "Lens",
    fps: "FPS",
    audio: "Audio",
    actor: "Actor",
    actionDesc: "Action / Description",
    producedBy: "Produced by Planify",
  },

  // Financials extra
  financialExtra: {
    editInvoice: "Edit Invoice",
    newInvoice: "New Invoice",
    editInvoiceDetails: "Edit invoice details",
    newInvoiceDetails: "Add a new invoice/income to the system",
    selectClient: "Select client",
    selectProjectOptional: "Select project (optional)",
    amountBeforeVat: "Amount before VAT (₪)",
    dueDate: "Due Date",
    externalInvoiceLink: "External invoice link",
    updateInvoice: "Update Invoice",
    addInvoice: "Add Invoice",
    editExpense: "Edit Expense",
    newExpense: "New Expense",
    editExpenseDetails: "Edit expense details",
    newExpenseDetails: "Add a new expense to the system",
    amount: "Amount (₪)",
    vendor: "Vendor",
    attachReceipt: "Attach receipt / PDF",
    clickToAttach: "Click to attach file (PDF, JPG, PNG)",
    updateExpense: "Update Expense",
    addExpense: "Add Expense",
    editEquipment: "Edit Equipment",
    newEquipment: "Add New Equipment",
    purchasePriceLabel: "Purchase Price (₪)",
  },

  // Financials page (table headers, stat cards, actions)
  financialPage: {
    uploadDocument: "Upload Document",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    selectMonth: "Select month",
    dateFilter: "Date filter",
    fromDate: "From date",
    toDate: "To date",
    clearFilter: "Clear filter",
    revenuePaid: "Revenue (Paid)",
    openInvoices: "Open Invoices",
    expenses: "Expenses",
    profitLoss: "Total Profit & Loss",
    fixedExpenses: "Fixed Expenses",
    number: "Number",
    dueDate: "Due Date",
    validUntil: "Valid Until",
    viewInvoice: "View Invoice",
    changeStatus: "Change Status",
    current: "(current)",
    editAction: "Edit",
    deleteAction: "Delete",
    monthNames: [
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December",
    ],
  },

  // Document upload dialog
  docUpload: {
    scanTitle: "AI Document Scan",
    scanDesc: "Upload an invoice or receipt — AI will scan and extract the data automatically",
    dragOrClick: "Drag a file here, or click to upload",
    allowedFormats: "PDF · JPG · JPEG · PNG only",
    aiVisionLabel: "AI Vision scans invoices",
    scanning: "Scanning with AI Vision...",
    identifyingFields: "Identifying type, amount, vendor, and date",
    pleaseWait: "Please wait",
    invalidDocTitle: "Please upload a financial document only",
    invalidDocDesc: "The uploaded document is not an invoice, receipt, or financial document",
    tryAgain: "Try again",
    scannedSuccess: "Data scanned successfully",
    income: "Income",
    expense: "Expense",
    docType: "Document type",
    expenseType: "Expense",
    invoiceType: "Invoice / Income",
    amountLabel: "Amount (₪)",
    clientOptional: "Client (optional)",
    noClient: "No client",
    categoryLabel: "Category",
    vendorLabel: "Vendor",
    savingLabel: "Saving...",
    saveExpense: "Save Expense",
    saveInvoice: "Save Invoice",
    fileOnlyError: "Only PDF, JPG, JPEG, PNG files allowed",
    parseError: "Error analyzing document",
    scanError: "Scan error",
    saveError: "Save error",
  },

  // Calendar page extra
  calendarPage: {
    selectClient: "Select Client",
    addToGCal: "Add to Google Calendar",
    selectEventForGCal: "Select event to add to Google Calendar",
    noEventsInView: "No events in current view",
    exportLabel: "Export",
    newShort: "New",
    clientPrefix: "Client",
  },

  // Calendar export extra (platform labels)
  calendarExportExtra: {
    platformShoot: "Shoot",
    platformYouTube: "YouTube",
    platformReel: "Reel",
  },

  // Inspiration extras
  inspirationExtra: {
    editInspiration: "Edit Inspiration",
    editDetails: "Edit inspiration details",
    addToBoard: "Add new inspiration to the board",
    titleRequired: "Title *",
    linkLabel: "Link",
    categoryRequired: "Category *",
    noCategoriesYet: "No categories yet — close and click \"Categories\" to create one",
    selectCategory: "Select category",
    needCategoryFirst: "You must create at least one category before saving",
    saveError: "Save error",
    openLink: "Open link",
    categoriesBtn: "Categories",
    inspirationRefs: "Inspiration references",
    manageCategories: "Manage Categories",
    manageCategoriesDesc: "Add, edit, or delete inspiration categories",
    noCategoriesEmpty: "No categories yet. Add one below.",
    newCategory: "New Category",
    categoryNamePlaceholder: "Category name...",
    createError: "Error creating category",
    updateError: "Error updating category",
    deleteError: "Error deleting category",
  },

  // Projects page extras
  projectsPage: {
    addToGCal: "Add to Google Calendar",
    createDriveFolder: "Create Drive Folder",
    noClientLabel: "No Client",
    driveSetupRequired: "Google Drive connection requires setup.",
    driveFolderError: "Error creating folder",
  },

  // Contacts page extras
  contactsPage: {
    contactsFeature: "Contacts",
  },

  // Subscriptions dialog extras
  subscriptionExtra: {
    editSubscription: "Edit Subscription",
    editDetails: "Edit subscription details",
    addNew: "Add a new subscription to the system",
    serviceName: "Service Name",
    billingCycle: "Billing Cycle",
    amountLabel: "Amount (₪)",
    nextBilling: "Next Billing",
  },

  // Travel dialog extras
  travelExtra: {
    editTrip: "Edit Trip",
    editDetails: "Edit trip details",
    addNew: "Add a new trip to the log",
    purposeLabel: "Purpose",
  },

  // Asset dialog extras
  assetExtra: {
    editAsset: "Edit Asset",
    editDetails: "Edit asset details",
    addNew: "Add a new asset to the library",
    nameRequired: "Name *",
    typeRequired: "Type *",
    sourceLabel: "Source",
    linkLabel: "Link",
    openLabel: "Open",
  },

  // Assets page extras
  assetsPage: {
    nameCol: "Name",
    typeCol: "Type",
    sourceCol: "Source",
    linkCol: "Link",
    notesCol: "Notes",
    actionsCol: "Actions",
  },

  // Quick links widget
  quickLinksExtra: {
    linkNamePlaceholder: "Link name",
  },

  // Todo widget
  todoExtra: {
    dailyTasks: "Daily Tasks",
    limitReached: "Limit of {limit} tasks — press Enter to upgrade",
  },

  // Layout / meta
  meta: {
    description: "The smart tool for managing your productions — clients, projects, scripts, and content calendars in one place.",
  },
} as const;
