// Hebrew labels for the entire app
export const he = {
  // Navigation
  nav: {
    dashboard: "לוח בקרה",
    projects: "פרויקטים",
    clients: "לקוחות",
    equipment: "ציוד",
    financials: "כספים",
    calendar: "לוח תוכן",
    contacts: "אנשי קשר",
    subscriptions: "הוצאות חודשיות",
    travelLog: "יומן נסיעות",
    assets: "רישיונות",
    inspiration: "השראה",
    cheatSheets: "מדריכים",
    scripts: "תסריטים",
    moodboard: "Moodboard",
    billing: "מנוי ותמחור",
    more: "עוד",
  },

  // Dashboard
  dashboard: {
    title: "לוח בקרה",
    activeProjects: "פרויקטים פעילים",
    upcomingShoots: "אירועים קרובים",
    pendingDeadlines: "דדליינים ממתינים",
    monthlyRevenue: "הכנסה החודש",
    outstandingInvoices: "חשבוניות פתוחות",
    conversionRate: "יחס המרה",
    recentProjects: "פרויקטים אחרונים",
    recentClients: "לקוחות אחרונים",
    noProjects: "אין פרויקטים פעילים",
    noShoots: "אין אירועים קרובים",
    newLeads: "לידים חדשים",
    pendingResponse: "ממתינים למענה",
    tasks: "משימות",
    openInvoices: "חשבוניות פתוחות",
    needsAttention: "דורש טיפול עכשיו",
    staleLeadMsg: "לא היה מענה",
    days: "ימים",
    deadlineTomorrow: "דדליין מחר",
    overdueInvoice: "באיחור",
    todaySchedule: "היום",
    noContentToday: "אין תוכן מתוכנן להיום",
    quickActions: "פעולות מהירות",
    addLead: "הוסף ליד",
    createProject: "צור פרויקט",
    addTask: "הוסף משימה",
    createQuote: "צור הצעת מחיר",
    leadsOverTime: "לידים לאורך זמן",
    leadSources: "מקורות לידים",
  },

  // Projects
  project: {
    title: "פרויקטים",
    newProject: "פרויקט חדש",
    phases: {
      // Legacy
      pre_production:    "לפני הצילומים",
      production:        "ימי צילום",
      post_production:   "עריכה",
      delivered:         "הושלם",
      revisions:         "תיקונים",
      // Photography
      coordination:      "תיאום",
      shoot_day:         "יום הצילום",
      shoot_days:        "ימי הצילום",
      selection:         "ברירה",
      editing:           "עריכה",
      gallery_delivery:  "גלריה למסירה",
      // Video / Content
      brief:             "בריף",
      planning:          "תכנון",
      monthly_planning:  "תכנון חודשי",
      research:          "מחקר",
      recording:         "הקלטה",
      writing:           "כתיבה",
      graphics:          "גרפיקה",
      waiting_approval:  "ממתין לאישור",
      published:         "פורסם",
      scheduling:        "תזמון",
      active:            "פעיל",
      // Editing
      materials_received: "חומרים התקבלו",
      first_cut:          "גרסה ראשונה",
      draft:              "טיוטה",
    },
    statuses: {
      pitching:       "בגיבוש",
      scripting:      "כתיבת תסריט",
      moodboards:     "בניית תדמית",
      location_scouting: "חיפוש לוקיישן",
      scheduled:      "מתוכנן",
      shooting:       "בצילומים",
      wrapping:       "סיום צילומים",
      ingest_sync:    "העברת חומרים",
      rough_cut:      "גרסה ראשונה",
      revisions_v1:   "תיקון ראשון",
      revisions_v2:   "תיקון שני",
      color_sound:    "גימור",
      final_delivery: "מסירה ללקוח",
      delivered:      "הושלם",
      archived:       "בארכיון",
    },
    types: {
      // Legacy (kept for backward compat)
      youtube:     "סרטון YouTube",
      music_video: "קליפ מוזיקלי",
      commercial:  "פרסומת",
      corporate:   "תדמית",
      social:      "סושיאל",
      // Photography
      wedding:             "חתונה",
      bar_bat_mitzva:      "בר / בת מצווה",
      event_photo:         "אירוע",
      portrait:            "פורטרט / מיני סשן",
      product_photography: "צילום מוצר",
      real_estate:         'נדל"ן',
      fashion:             "אופנה / מוד",
      family:              "משפחה / הריון",
      // Video
      podcast:   "פודקאסט",
      interview: "כתבה / ריאיון",
      bts:       "BTS",
      // Content
      reel:             "ריל / סטורי",
      post_carousel:    "פוסט / קרוסלה",
      page_management:  "ניהול עמוד (ריטיינר)",
      content_strategy: "אסטרטגיית תוכן",
      // Editing
      video_editing:   "עריכת וידאו",
      podcast_editing: "עריכת פודקאסט",
      motion_graphics: "גרפיקה / מושן",
    },
    shootDate: "תאריך",
    deadline:  "דדליין",
    budget:    "תקציב",
    client:    "לקוח",
    description: "תיאור",
    type: "סוג פרויקט",
  },

  // Clients
  client: {
    title: "לקוחות",
    newClient: "לקוח חדש",
    newLead: "ליד חדש",
    name: "שם",
    email: "אימייל",
    phone: "טלפון",
    company: "חברה",
    notes: "הערות",
    type: "סוג",
    types: {
      lead: "ליד",
      client: "לקוח",
    },
    leadSource: "מקור ליד",
    leadSources: {
      linkedin: "LinkedIn",
      organic: "אורגני",
      referral: "הפניה",
      website: "אתר",
      social: "רשתות חברתיות",
      other: "אחר",
    },
    leadStatus: "סטטוס ליד",
    leadStatuses: {
      new: "חדש",
      contacted: "נוצר קשר",
      qualified: "מתאים",
      proposal_sent: "הצעה נשלחה",
      won: "נסגר",
      lost: "אבוד",
    },
    interactions: "היסטוריית אינטראקציות",
    interactionTypes: {
      call: "שיחה",
      email: "אימייל",
      meeting: "פגישה",
      note: "הערה",
    },
  },

  // Equipment
  equipment: {
    title: "ציוד",
    newItem: "פריט חדש",
    name: "שם",
    type: "סוג",
    category: "קטגוריה",
    brand: "מותג",
    model: "דגם",
    serialNumber: "מספר סריאלי",
    purchasePrice: "מחיר רכישה",
    status: "סטטוס",
    categories: {
      camera: "מצלמה",
      lens: "עדשה",
      drone: "רחפן",
      lighting: "תאורה",
      audio: "אודיו",
      grip: "גריפ",
      other: "אחר",
    },
    statuses: {
      available: "זמין",
      rented: "מושכר",
      in_repair: "בתיקון",
      retired: "לא בשימוש",
    },
  },

  // Financials
  financial: {
    title: "כספים",
    quotes: "הצעות מחיר",
    invoices: "חשבוניות",
    expenses: "הוצאות",
    newQuote: "הצעת מחיר חדשה",
    newInvoice: "חשבונית חדשה",
    newExpense: "הוצאה חדשה",
    subtotal: "סכום ביניים",
    tax: 'מע"מ (17%)',
    total: 'סה"כ',
    status: "סטטוס",
    quoteStatuses: {
      draft: "טיוטה",
      sent: "נשלחה",
      accepted: "אושרה",
      declined: "נדחתה",
    },
    invoiceStatuses: {
      draft: "טיוטה",
      sent: "נשלחה",
      paid: "שולמה",
      overdue: "באיחור",
      cancelled: "בוטלה",
    },
    expenseCategories: {
      overhead: "הוצאה חודשית קבועה",
      project: "הוצאה לפרויקט",
      gear_purchase: "רכישת ציוד",
      vehicle_travel: "רכב/נסיעות",
      other: "אחר",
    },
  },

  // Content Calendar
  calendar: {
    title: "לוח תוכן",
    newContent: "תוכן חדש",
    contentTypes: {
      client_shoot: "צילום לקוח",
      youtube_long: "יוטיוב ארוך",
      short_form: "קצר",
    },
    statuses: {
      planned: "מתוכנן",
      editing: "בעריכה",
      ready: "מוכן לפרסום",
      published: "פורסם",
      event: "אירוע",
    },
    newBoard: "לוח חדש",
    boardTitlePlaceholder: "שם הלוח...",
    noClient: "ללא לקוח",
    noProject: "ללא פרויקט",
    items: "פריטים",
    noBoards: "אין לוחות תוכן",
    createFirst: "צור לוח ראשון",
    noContent: "אין תוכן מתוכנן",
    upcomingContent: "תוכן וצילומים קרובים",
    dayNames: ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת"],
    selectEvent: "בחר אירוע להוספה לגוגל קלנדר",
    noEventsInView: "אין אירועים בתצוגה הנוכחית",
    newShort: "חדש",
  },

  // Contacts / Crew Rolodex
  contacts: {
    title: "אנשי קשר",
    newContact: "איש קשר חדש",
    categories: {
      editor: "עורך",
      stills_photographer: "צלם סטילס",
      video_photographer: "צלם וידאו",
      lighting: "תאורן",
      director: "במאי",
      art: "ארט",
      production_assistant: "עוזר הפקה",
      producer: "מפיק",
      three_d: "תלת מימד",
      sound_designer: "מעצב סאונד",
      makeup: "איפור",
      actor: "שחקן/ית",
      rental_house: "השכרת ציוד",
      studio: "סטודיו",
      social_manager: "מנהל/ת סושיאל",
    },
  },

  // Subscriptions
  subscriptions: {
    title: "הוצאות חודשיות",
    newSubscription: "מנוי חדש",
    totalMonthly: "עלות חודשית כוללת",
    cycles: {
      monthly: "חודשי",
      yearly: "שנתי",
    },
    statuses: {
      active: "פעיל",
      cancelled: "בוטל",
    },
  },

  // Travel Log
  travelLog: {
    title: "יומן נסיעות",
    newEntry: "נסיעה חדשה",
    totalKm: "סה״כ ק״מ החודש",
    origin: "מוצא",
    destination: "יעד",
    kilometers: "ק״מ",
  },

  // Asset Library
  assets: {
    title: "רישיונות",
    newAsset: "נכס חדש",
    types: {
      music: "מוזיקה",
      sfx: "אפקטים קוליים",
      font: "פונט",
      stock_footage: "סטוק וידאו",
    },
  },

  // Inspiration Board
  inspiration: {
    title: "לוח השראה",
    newItem: "השראה חדשה",
    categories: {
      lighting: "תאורה",
      editing: "עריכה",
      hooks: "הוקים",
      thumbnails: "תמונות ממוזערות",
    },
  },

  // Cheat Sheets
  cheatSheets: {
    title: "מדריכים ונהלים",
    newSheet: "מדריך חדש",
  },

  // Scripts
  scripts: {
    title: "תסריטים",
    newScript: "תסריט חדש",
    untitled: "תסריט ללא כותרת",
    editor: {
      placeholder: "התחל לכתוב את התסריט שלך...",
      saving: "שומר...",
      saved: "נשמר",
      unsaved: "לא נשמר",
    },
    ai: {
      title: "AI Copilot",
      generateTab: "צור",
      upgradeTab: "שדרג",
      instructTab: "הוראות",
      generatePlaceholder: "תאר את התסריט שאתה רוצה (נושא, אורך, פלטפורמה)...",
      instructPlaceholder: "ספר ל-AI מה לשנות...",
      generateButton: "צור תסריט",
      upgradeButton: "שדרג תסריט",
      applyButton: "החל",
      generating: "יוצר...",
      upgrading: "משדרג...",
      applying: "מחיל...",
    },
    noScripts: "אין תסריטים עדיין",
    deleteConfirm: "האם למחוק את התסריט?",
  },

  // Dashboard Widgets
  widgets: {
    quickNotes: "פתקים מהירים",
    quickNotesPlaceholder: "רשום רעיונות כאן...",
    todos: "משימות יומיות",
    todosPlaceholder: "הוסף משימה...",
    quickLinks: "קישורים מהירים",
    newLink: "קישור חדש",
    gearReset: "סטטוס ציוד",
    gearItems: {
      sd_cards: "כרטיסי SD",
      footage: "גיבוי חומרים",
      batteries: "סוללות",
    },
    gearReady: "מוכן",
    gearNotReady: "דורש טיפול",
  },

  // Common
  common: {
    type: "סוג",
    save: "שמור",
    saving: "שומר...",
    cancel: "ביטול",
    delete: "מחק",
    deleting: "מוחק...",
    edit: "ערוך",
    add: "הוסף",
    search: "חיפוש",
    searchPlaceholder: "חיפוש...",
    filter: "סינון",
    noResults: "לא נמצאו תוצאות",
    loading: "טוען...",
    currency: "₪",
    signOut: "יציאה מהמערכת",
    billingPlan: "תוכנית המנוי",
    back: "חזרה",
    close: "סגור",
    confirm: "אישור",
    name: "שם",
    email: "אימייל",
    phone: "טלפון",
    notes: "הערות",
    date: "תאריך",
    status: "סטטוס",
    actions: "פעולות",
    active: "פעיל",
    inactive: "לא פעיל",
    all: "הכל",
    none: "ללא",
    optional: "אופציונלי",
    required: "חובה",
    new: "חדש",
    update: "עדכון",
    create: "צור",
    description: "תיאור",
    title: "כותרת",
    category: "קטגוריה",
    project: "פרויקט",
    client: "לקוח",
    selectClient: "בחר לקוח",
    selectProject: "בחר פרויקט",
    noClient: "ללא לקוח",
    noProject: "ללא פרויקט",
    addNewClient: "הוסף לקוח חדש",
    newClientName: "שם הלקוח החדש...",
    deleteConfirmTitle: "אישור מחיקה",
    deleteConfirmText: "האם אתה בטוח? פעולה זו אינה ניתנת לביטול.",
    addSocialNetwork: "הוסף רשת חברתית",
    activeClient: "לקוח פעיל",
    editClient: "עריכת לקוח",
    newClientTitle: "לקוח חדש",
    editContact: "עריכת איש קשר",
    newContactTitle: "איש קשר חדש",
    editProject: "עריכת פרויקט",
    newProjectTitle: "פרויקט חדש",
    enterProjectDetails: "הזן את פרטי הפרויקט החדש",
    editProjectDetails: "ערוך את פרטי הפרויקט",
    projectName: "שם פרויקט",
    createProject: "צור פרויקט",
    addTask: "הוסף משימה...",
    removeFromProject: "הסר מהפרויקט",
    backToProjects: "חזרה לפרויקטים",
    backToBoards: "חזרה ללוחות",
    clickAgainToDelete: "לחץ שוב למחיקה",
    noTasks: "אין משימות",
    noScriptsLinked: "אין תסריטים",
    noMoodboardsLinked: "אין Moodboards",
    noContactsLinked: "אין אנשי קשר",
    noCalendarLinked: "אין תוכן מתוכנן",
    allLinked: "הכל כבר משויך",
    allClients: "כל הלקוחות",
    allCategories: "כל הקטגוריות",
    perDay: "/ יום",
    budget: "תקציב",
    deadline: "דדליין",
    company: "חברה",
    website: "אתר",
    color: "צבע",
    export: "ייצוא",
    addToGCal: "הוסף לגוגל קלנדר",
    events: "אירועים",
    activeClients: "לקוחות פעילים",
    totalClients: "סה״כ לקוחות",
    noProjects: "אין פרויקטים",
    noContent: "אין תוכן",
    linkToProject: "שייך לפרויקט",
    feedback: "פידבק",
    sendFeedback: "שלח פידבק",
    sending: "שולח...",
    ratingOptional: "דירוג (אופציונלי)",
    feedbackQuestion: "מה דעתך? מה חסר? מה עבד מצוין?",
    writeHere: "כתוב כאן...",
    thankYouFeedback: "תודה על הפידבק!",
    helpsUsImprove: "זה עוזר לנו להשתפר",
    sendAnother: "שלח עוד פידבק",
    editContent: "עריכת תוכן",
    newContentTitle: "תוכן חדש",
    editContentDetails: "ערוך את פרטי התוכן",
    enterContentDetails: "הוסף תוכן חדש ללוח",
    updateContent: "עדכון תוכן",
    addContent: "הוספת תוכן",
    deleteContent: "מחיקה",
    dailyRate: "תעריף יומי",
    addNewCategory: "הוסף קטגוריה חדשה",
    newCategoryName: "שם קטגוריה חדשה...",
    accountSettings: "הגדרות חשבון",
    billingPayments: "מנוי ותשלומים",
    signOutAction: "התנתקות",
    editClientForm: "טופס עריכת לקוח",
    newClientForm: "טופס יצירת לקוח חדש",
    editContactDetails: "ערוך את פרטי איש הקשר",
    newContactDetails: "הוסף איש קשר חדש לרשת",
    deleteTask: "מחק משימה",
    tasks: "משימות",
    statusPlanning: "תכנון",
    statusInProgress: "בביצוע",
    statusReview: "ממתין לאישור",
    statusDone: "הושלם",
    days: "ימים",
    assignedToProject: "משויך לפרויקט",
    noProjectsYet: "אין פרויקטים עדיין",
    clickNewProject: 'לחץ על "פרויקט חדש" כדי להתחיל',
    tasksLabel: "משימות",
  },

  // Auth
  auth: {
    welcomeBack: "ברוך שובך ל-Planify",
    signInSubtitle: "היכנס לחשבון שלך להמשיך",
    email: "אימייל",
    password: "סיסמה",
    signInButton: "כניסה לחשבון",
    signingIn: "מתחבר...",
    orContinueWith: "או המשך עם",
    noAccount: "אין לך חשבון?",
    freeSignUp: "הרשמה חינם",
    invalidCredentials: "כתובת האימייל או הסיסמה שגויים",
    createAccount: "צור חשבון ב-Planify",
    createAccountSubtitle: "מערכת הניהול לצלמים ומפיקים",
    fullName: "שם מלא",
    createAccountButton: "יצירת חשבון חינם",
    creatingAccount: "יוצר חשבון...",
    agreeToTerms: "בהרשמה אתה מסכים לתנאי השימוש ומדיניות הפרטיות",
    alreadyHaveAccount: "כבר יש לך חשבון?",
    signIn: "כניסה",
    signUpFailed: "משהו השתבש. נסה שוב.",
    signUpSuccessSignInFailed: "ההרשמה הצליחה אך הכניסה נכשלה. נסה להיכנס ידנית.",
    minChars: "לפחות 6 תווים",
    secureLogin: "גישה מאובטחת",
    dataProtected: "המידע שלך מוגן ומוצפן",
    secureSignUp: "הרשמה מאובטחת — ללא כרטיס אשראי",
    agreeCheckbox: "אני מסכים/ה לתנאי השימוש ומדיניות הפרטיות",
    freeTrial: "ניסיון חינם ל-3 ימים",
    termsLink: "תנאי השימוש",
    privacyLink: "מדיניות הפרטיות",
  },

  // Profile / Settings
  profile: {
    accountSettings: "הגדרות חשבון",
    userDetails: "פרטי המשתמש שלך",
    fullName: "שם מלא",
    notSet: "לא הוגדר",
    emailAddress: 'כתובת דוא"ל',
    security: "אבטחה",
    securityDesc: "סיסמה מוצפנת · אימות בכניסה",
    languageLabel: "שפה / Language",
    changePassword: "שינוי סיסמה",
    changePasswordDesc: "בחר סיסמה חזקה של לפחות 6 תווים",
    currentPassword: "סיסמה נוכחית",
    currentPasswordPlaceholder: "הזן סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmNewPassword: "אימות סיסמה חדשה",
    confirmNewPasswordPlaceholder: "חזור על הסיסמה החדשה",
    savePassword: "שמור סיסמה",
    passwordChanged: "הסיסמה שונתה בהצלחה",
    passwordsDoNotMatch: "הסיסמאות החדשות אינן תואמות",
    passwordTooShort: "הסיסמה החדשה חייבת להכיל לפחות 6 תווים",
    passwordChangeError: "שגיאה בשינוי הסיסמה",
    networkError: "שגיאת רשת, נסה שוב",
  },

  // Billing
  billing: {
    transparentPricing: "תמחור שקוף וגמיש",
    allIncluded: "הכל כלול. ללא הפתעות.",
    cancelAnytime: "ביטול חופשי בכל עת — אין חוזים, אין קנסות.",
    monthly: "חודשי",
    annual: "שנתי",
    savings: "חיסכון ₪118",
    freePlan: "Planify חינמי",
    trialDays: "ניסיון של 3 ימים",
    forTrialDays: "ל-3 ימי ניסיון",
    currentPlan: "התוכנית הנוכחית",
    freeFeature1: "1 פרויקט ראשון",
    freeFeature2: "3 לקוחות",
    freeFeature3: "גישה מלאה ל-3 ימים",
    freeFeature4: "ללא כרטיס אשראי",
    proAnnual: "Planify Pro שנתי",
    proMonthly: "Planify Pro חודשי",
    annualBilling: "חיוב שנתי",
    monthlyBilling: "חיוב חודשי, ביטול בכל עת",
    perMonth: "/ חודש",
    annualPriceSuffix: "/ חודש — חיוב ₪590 לשנה",
    monthlyPriceSuffix: "/ חודש — חיוב חודשי",
    twoMonthsFree: "✓ חודשיים חינם לעומת מנוי חודשי",
    startNow: "התחל עכשיו",
    bestValue: "✦ הכי משתלם",
    proFeature1: "פרויקטים ללא הגבלה",
    proFeature2: "לקוחות ואנשי קשר ללא הגבלה",
    proFeature3: "כל פיצ'רי המערכת",
    proFeature4: "חשבוניות והצעות מחיר",
    proFeature5: "לוח תוכן + תסריטים",
    proFeature6: "לוח השראה ומודבורד",
    proFeatureAnnual1: "עדיפות בתמיכה",
    proFeatureAnnual2: "חודשיים חינם",
    fullComparison: "השוואה מלאה",
    feature: "פיצ'ר",
    unlimited: "ללא הגבלה",
    trustCancel: "ביטול בכל עת",
    trustCancelDesc: "אין חוזים, אין קנסות.",
    trustUpgrade: "שדרוג מיידי",
    trustUpgradeDesc: "עוברים לתוכנית גבוהה יותר בלחיצה.",
    trustData: "נתונים שלך",
    trustDataDesc: "כל הנתונים נשמרים גם לאחר הביטול.",
    manageSubscription: "לניהול המנוי הנוכחי",
    clickHere: "לחץ כאן ←",
    trialExpiredTitle: "תקופת הניסיון שלך הסתיימה",
    trialExpiredDesc: "ה-3 ימים חלפו. בחר תוכנית כדי להמשיך להשתמש במערכת.",
    // Billing comparison table feature labels
    featureProjects: "פרויקטים",
    featureClients: "לקוחות",
    featureContacts: "אנשי קשר",
    featureDocuments: "מסמכים להעלאה",
    featureScripts: "תסריטים",
    featureInspiration: "לוחות השראה (פריטים)",
    featureMoodboards: "לוחות מודבורד",
    featureDailyTasks: "משימות יומיות",
    featureInvoices: "חשבוניות והצעות מחיר",
    featureCalendar: "לוח תוכן",
    featureExpenses: "ניהול הוצאות",
    featurePrioritySupport: "עדיפות בתמיכה",
    // Checkout
    goBack: "חזור",
    completePurchase: "סיום רכישה",
    cardNumber: "מספר כרטיס",
    cardholderName: "שם בעל הכרטיס",
    expiryDate: "תאריך תפוגה",
    creditCardDetails: "פרטי כרטיס אשראי",
    secureSSL: "תשלום מאובטח SSL",
    pciEncryption: "הצפנה PCI DSS",
    cancelAnytimeNoCharge: "ביטול בכל עת, ללא חיוב נוסף",
    processingPayment: "מעבד תשלום...",
    payNow: "שלם",
    now: "עכשיו",
    agreeTerms: 'על ידי לחיצה על "שלם" אתה מסכים ל',
    termsOfService: "תנאי השירות",
    and: "ול",
    privacyPolicy: "מדיניות הפרטיות",
    invalidCardNumber: "מספר כרטיס אינו תקין",
    enterCardholderName: "יש להזין שם בעל הכרטיס",
    invalidExpiry: "תאריך תפוגה אינו תקין",
    invalidCVV: "CVV אינו תקין",
    paymentError: "שגיאה בעיבוד התשלום",
    // Settings/Billing
    subscriptionAndPayments: "מנוי ותשלומים",
    subscriptionManagement: "ניהול המנוי, שיטת התשלום ואפשרויות החיוב",
    welcomePro: "ברוך הבא לתוכנית הפרו!",
    upgradeSuccess: "השדרוג הצליח. כעת יש לך גישה לכל הפיצ'רים.",
    activePlan: "תוכנית פעילה",
    statusLabel: "סטטוס",
    canceled: "בוטל",
    activeStatus: "פעיל",
    freeStatus: "חינמי",
    accessUntil: "גישה עד",
    nextRenewal: "חידוש הבא",
    planQuotas: "מכסות התוכנית",
    projectsQuota: "פרויקטים",
    contactsQuota: "אנשי קשר",
    documentsQuota: "מסמכים",
    scriptsQuota: "תסריטים",
    includedInPlan: "מה כלול בתוכנית שלך",
    includedFeature1: "כל פיצ'רי המערכת",
    includedFeature2: "חשבוניות והצעות מחיר",
    includedFeature3: "לוח תוכן + תסריטים + השראה",
    includedFeature4: "גישה לכל העדכונים העתידיים",
    upgradeForMore: "שדרג לקבלת מכסות גדולות יותר וגישה לכל הפיצ'רים",
    upgradeToPro: "שדרג לפרו",
    paymentMethod: "שיטת תשלום",
    comingSoon: "בקרוב",
    paymentMethodDesc: "ניהול שיטת התשלום יהיה זמין לאחר חיבור מערכת הסליקה (Stripe).",
    paymentMethodNote: "לאחר החיבור — הכפתור יפתח את פורטל הלקוח של Stripe לניהול הכרטיס.",
    cancelSubscription: "ביטול מנוי",
    cancelDesc: "לאחר הביטול תמשיך ליהנות מהגישה עד סוף תקופת החיוב הנוכחית.",
    cancelConfirmTitle: "ביטול המנוי",
    cancelConfirmDesc: "האם אתה בטוח שברצונך לבטל את המנוי? תאבד גישה לפיצ'רים הפרמיום בסוף מחזור החיוב הנוכחי.",
    keepSubscription: "שמור על המנוי שלי",
    yesCancelSubscription: "כן, בטל את המנוי",
    canceling: "מבטל...",
    canceledNotice: "המנוי שלך בוטל. תוכל להמשיך להשתמש בפיצ'רים הפרמיום עד",
    loadError: "לא ניתן לטעון את פרטי המנוי. נסה לרענן את הדף.",
    refresh: "רענן",
  },

  // Moodboard
  moodboard: {
    title: "Moodboard",
    subtitle: "עצב ואסוף השראה ויזואלית לפרויקטים שלך",
    newMoodboard: "Moodboard חדש",
    noMoodboards: "אין Moodboards עדיין",
    noMoodboardsDesc: "צור Moodboard חדש כדי להתחיל לאסוף השראה",
    createFirst: "צור Moodboard ראשון",
    updated: "עודכן",
    deleteConfirm: "למחוק את הלוח?",
    writeHere: "כתוב כאן...",
    addDescription: "הוסף תיאור...",
    editLink: "ערוך קישור",
    linkDescription: "תיאור הקישור",
    newNote: "הערה חדשה",
    newHeading: "כותרת חדשה",
    heading: "כותרת",
    deleteNode: "מחק",
    imageAlt: "תמונה",
    linkTab: "קישור",
    uploadTab: "העלאה",
    cameraTab: "מצלמה",
    showImage: "הצג תמונה",
    clickToSelectImage: "לחץ לבחירת תמונה",
    dragOrClick: "גרור תמונה לכאן או לחץ לבחירה",
    openCamera: "פתח מצלמה",
    maxSize: "מקסימום 8MB",
    addImage: "הוסף תמונה",
    uploadFileNote: "לחץ לצירוף קובץ (PDF, JPG, PNG)",
    uploading: "מעלה...",
    typeText: "הקלד טקסט...",
    textColor: "טקסט",
    bgColor: "רקע",
    noBg: "ללא רקע",
    defaultFont: "ברירת מחדל",
    rect: "מלבן",
    circle: "עיגול",
    triangle: "משולש",
    diamond: "מעוין",
    star: "כוכב",
    arrow: "חץ",
    contentBoards: "לוחות תוכן",
    pasteImageLink: "הדבק קישור לתמונה...",
    descriptionOptional: "תיאור (אופציונלי)",
    titleOptional: "כותרת (אופציונלי)",
    headingPlaceholder: "כותרת...",
    save: "שמור",
    link: "קישור",
    rotate: "סובב",
    fillColor: "צבע מילוי",
    fillLabel: "מילוי",
    strokeColor: "צבע קו",
    strokeLabel: "קו",
    strokeWidth: "עובי",
    color: "צבע",
    clear: "נקה",
    rows: "שורות",
    columns: "עמודות",
    stickyNote: "פתק",
    image: "תמונה",
    text: "טקסט",
    table: "טבלה",
    shape: "צורה",
    draw: "ציור",
    pen: "עט",
    eraser: "מחק",
    finish: "סיים",
    back: "חזרה",
    saving: "שומר...",
    saved: "נשמר",
    unsaved: "לא נשמר",
    add: "הוסף",
    maxSizeAlert: "מקסימום 8MB",
    maxSizeNote: "PNG, JPG, GIF, WEBP — עד 8MB",
    upgradeFeature: "פריטים בלוח תוכן",
    drawingAlt: "ציור",
    textColorTitle: "צבע טקסט",
    bgColorTitle: "צבע רקע",
  },

  // Tasks page
  tasks: {
    title: "משימות",
    activeCount: "פעילות",
    doneCount: "הושלמו",
    addNewTask: "הוסף משימה חדשה...",
    reachedLimit: "הגעת למגבלת {limit} משימות — לחץ לשדרוג",
    allFilter: "הכל",
    activeFilter: "פעילות",
    doneFilter: "הושלמו",
    noDoneTasks: "עוד לא סיימת משימות",
    noTasksHere: "אין משימות כאן",
    upgradeUnlimited: "שדרג לפרו — משימות ללא הגבלה",
    freeLimit: "בתוכנית החינמית:",
    dailyTasks: "משימות יומיות",
    upgradeFeature1: "פרויקטים ולקוחות ללא הגבלה",
    upgradeFeature2: "חשבוניות והצעות מחיר",
    upgradeFeature3: "לוח השראה ותסריטים",
  },

  // Upgrade dialog
  upgrade: {
    reachedLimit: "הגעת למגבלה!",
    freeLimit: "בתוכנית החינמית ניתן להוסיף עד",
    upgradeForUnlimited: "שדרג לפרו וקבל גישה ללא הגבלה.",
    feature1: "פרויקטים, אנשי קשר ותסריטים ללא הגבלה",
    feature2: "חשבוניות, הצעות מחיר ולוח השראה",
    feature3: "גישה מלאה לכל כלי הניהול",
    upgradeNow: "שדרג לפרו עכשיו",
    maybeLater: "אולי מאוחר יותר",
  },

  // Theme toggle
  theme: {
    lightMode: "מצב יום",
    darkMode: "מצב לילה",
  },

  // Onboarding
  onboarding: {
    exit: "יציאה",
    envReady: "הסביבה מוכנה!",
    transferring: "מעביר אותך...",
    preparingEnv: "מכין לך את הסביבה...",
    oneSecond: "שנייה אחת",
    whatDoYouDo: "במה אתה עוסק?",
    selectMultiple: "ניתן לבחור יותר מאפשרות אחת",
    mainGoal: "מה המטרה הראשית שלך?",
    howDoYouWork: "איך אתה עובד?",
    selectTeamSize: "בחר גודל צוות",
    finish: "סיים",
    continueBtn: "המשך",
    goBack: "→ חזור",
    roles: {
      videographer: "צלם וידאו",
      videographerDesc: "מצלמים, עורכים, מעבירים",
      photographer: "צלם סטילס",
      photographerDesc: "צילום אנשי ומוצרים",
      smm: "מנהל סושיאל",
      smmDesc: "ריטיינרים ותוכן שוטף",
      editor: "עורך וידאו",
      editorDesc: "עריכה, גרפיקה, אנימציה",
      producer: "מפיק",
      producerDesc: "ניהול הפקות ולוגיסטיקה",
      agency: "סוכנות / סטודיו",
      agencyDesc: "צוות מלא, מספר לקוחות",
    },
    goals: {
      shoots_gear: "ניהול צילומים",
      shoots_gearDesc: "לוחות זמנים, לוגיסטיקה",
      retainer: "תוכן שוטף",
      retainerDesc: "ריטיינרים, קונטנט חודשי",
      financials: "חשבוניות וכספים",
      financialsDesc: "הכנסות, הוצאות, הצעות מחיר",
      scripts: "סקריפטים ויוצרות",
      scriptsDesc: "כתיבת סקריפטים, שוט ליסט",
    },
    teamSizes: {
      solo: "פרילנסר סולו",
      soloDesc: "עובד לבד בעיקר",
      small: "צוות קטן (2–5)",
      smallDesc: "שותף או כמה עובדים",
      studio: "סטודיו (5+)",
      studioDesc: "צוות מלא, מבנה ארגוני",
    },
  },

  // Admin
  admin: {
    dashboard: "לוח ניהול",
    dashboardDesc: "ניהול משתמשים ומנויים",
    totalUsers: "סה״כ משתמשים",
    free: "חינמי",
    proMonthly: "Pro חודשי",
    proAnnual: "Pro שנתי",
    mrr: "MRR",
    registeredThisWeek: "נרשמו השבוע",
    registeredThisMonth: "נרשמו החודש",
    incompleteOnboarding: "לא השלימו אונבורדינג",
    totalProjects: "סה״כ פרויקטים",
    totalScripts: "סה״כ תסריטים",
    totalContacts: "סה״כ אנשי קשר",
    avgPerUser: "ממוצע {avg} למשתמש",
    searchPlaceholder: "חפש לפי שם או אימייל...",
    user: "משתמש",
    subscription: "מנוי",
    expiry: "תוקף",
    statusCol: "סטטוס",
    joined: "הצטרף",
    changePlan: "שינוי מנוי",
    actionsCol: "פעולות",
    active: "פעיל",
    onboardingStatus: "אונבורדינג",
    resetPassword: "איפוס סיסמה",
    updateExpiry: "עדכון תוקף מנוי",
    deleteUser: "מחק משתמש",
    deleteConfirm: "מחק",
    cancelAction: "ביטול",
    newPasswordPlaceholder: "סיסמה חדשה...",
    updatePassword: "עדכן סיסמה",
    expiryTitle: "תוקף מנוי",
    updateBtn: "עדכן",
    removeExpiry: "הסר תוקף",
    passwordUpdated: "הסיסמה עודכנה בהצלחה",
    expiryUpdated: "תוקף המנוי עודכן",
    noUsersFound: "לא נמצאו משתמשים",
    feedbackTitle: "פידבק מהמשתמשים",
    noFeedback: "אין פידבק עדיין",
    anonymous: "אנונימי",
    deleteFeedback: "מחק פידבק",
  },

  // Welcome tour
  tour: {
    welcome: "ברוכים הבאים ל-Planify!",
    welcomeDesc: "המערכת שבנויה במיוחד לאנשי תוכן, מצלמים ומפיקים. בואו נסביר לך מה יש כאן בכמה שניות.",
    dashboardTitle: "לוח בקרה",
    dashboardDesc: "מבט מהיר על הפרויקטים הפעילים, הכנסות, צילומים קרובים ומשימות פתוחות — הכל במקום אחד.",
    projectsTitle: "פרויקטים",
    projectsDesc: "עקוב אחרי כל פרויקט מרגע הפנייה הראשונה ועד המסירה ללקוח — מאורגן לפי שלבים ברורים.",
    clientsTitle: "לקוחות",
    clientsDesc: "נהל לידים, לקוחות קיימים ואינטראקציות. ראה בקצב אחד מי מוכן לסגירה ומה הסטטוס של כל ליד.",
    financialsTitle: "כספים",
    financialsDesc: "שלח חשבוניות והצעות מחיר, עקוב אחרי הוצאות וראה את הרווח החודשי שלך בזמן אמת.",
    calendarTitle: "לוח תוכן",
    calendarDesc: "תכנן פוסטים, ריטיינרים וצילומים בלוח חודשי. ראה הכל בצורה ויזואלית ברורה.",
    scriptsTitle: "תסריטים",
    scriptsDesc: "כתוב ושמור תסריטים לסרטונים, ריילס ופרסומות. הכל מאורגן לפי פרויקט ומוכן להפקה.",
    contactsTitle: "אנשי קשר",
    contactsDesc: "שמור טלפונים, מיילים ופרטי קשר של צלמים, עורכים, לקוחות ושאר גורמים שאתה עובד איתם.",
    inspirationTitle: "לוח השראה",
    inspirationDesc: "אסוף תמונות, סרטונים ורפרנסים בקטגוריות. הדלק השראה לפרויקטים הבאים ושתף עם לקוחות.",
    skip: "דלג",
    prev: "הקודם",
    next: "הבא",
    letsStart: "בואו נתחיל",
    stepOf: "מתוך",
  },

  // Calendar export
  calendarExport: {
    exportToClient: "ייצוא ללקוח",
    allClients: "כל הלקוחות",
    layout: "תצוגה",
    grid: "לוח",
    list: "רשימה",
    themeLabel: "ערכת נושא",
    light: "בהיר",
    dark: "כהה",
    darkModeNote: "מצב כהה מתאים ללוגו לבן",
    brandColor: "צבע מותג",
    customColor: "צבע מותאם אישית",
    logo: "לוגו",
    clickToUploadLogo: "לחץ להעלאת לוגו",
    removeLogo: "הסר לוגו",
    zoomLabel: "זום תצוגה",
    exporting: "מייצא...",
    footerNote: "הלוגו, הצבעים והתוכן הם לצורך תצוגת לקוח בלבד",
    producedBy: "הופק ע\"י Planify",
    noContentThisMonth: "אין ימי תוכן בחודש זה",
    dateCol: "תאריך",
    productCol: "תוצר",
    platformCol: "פלטפורמה",
    exportPngFailed: "ייצוא PNG נכשל — נסה שוב",
    exportPdfFailed: "ייצוא PDF נכשל — נסה שוב",
    shoot: "צילום",
  },

  // Script editor specific
  scriptEditor: {
    podcast: "פודקאסט",
    commercial: "פרסומת",
    filterColumns: "סינון עמודות",
    close: "סגור",
    displayMode: "מצב תצוגה",
    showFrames: "הצג תמונה",
    storyboard: "סטורי\nבורד",
    cinematic: "קולנועי",
    foldRows: "קיפול שורות",
    open: "פתוח",
    folded: "מקופל",
    customShotNo: "מספור שוט מותאם",
    customShotNoDesc: "אפשר עריכת מספרים כ-1A, 2B",
    shotOrder: "סדר שוטים",
    ascending: "עולה",
    descending: "יורד",
    addFrame: "הוסף",
    action: "אקשן...",
    lensPlaceholder: "עדשה...",
    soundPlaceholder: "סאונד...",
    dialoguePlaceholder: "דיאלוג...",
    notePlaceholder: "הערה...",
    equipmentPlaceholder: "ציוד...",
    lightingPlaceholder: "תאורה...",
    actorPlaceholder: "שחקן...",
    propPlaceholder: "פרופ...",
    costumePlaceholder: "תלבושת...",
    makeupPlaceholder: "איפור...",
    addImageStoryboard: "הוסף תמונה",
    actionDesc: "אקשן / תיאור...",
    errorTryAgain: "שגיאה. נסה שוב.",
    deleteScript: "למחוק את התסריט?",
    createFirstScript: "צור תסריט ראשון",
    createFirstScriptDesc: "צור תסריט חדש כדי להתחיל",
    // Tabs
    tabScript: "תסריט",
    tabShotList: "שוט ליסט",
    tabCallSheet: "קול שיט",
    // Top bar
    scriptsBack: "תסריטים",
    scriptTitlePlaceholder: "כותרת התסריט...",
    customPlatformPlaceholder: "פלטפורמה מותאמת...",
    linkedProject: "פרויקט",
    noProject: "ללא פרויקט",
    assignToProject: "שייך לפרויקט",
    saving: "שומר...",
    saved: "נשמר",
    autoSave: "שמור אוטומטי",
    other: "אחר...",
    // Script tab
    scriptPlaceholder: "התחל לכתוב את התסריט שלך...",
    addToShotList: "הוסף לשוט ליסט",
    aiHelp: "עזרה מ-AI",
    writingAssistant: "עוזר כתיבה",
    generateScript: "צור תסריט",
    fromPrompt: "מפרומפט עם AI",
    upgradeScript: "שדרג תסריט",
    upgradeScriptDesc: "הוק, פייסינג וניסוח",
    aiPromptPlaceholder: "לדוג׳: וידאו על מוצר תכשיטים, קהל 25-35, טון שאיפתי",
    generate: "צור",
    cancel: "ביטול",
    chatPlaceholder: "מה לשנות? (Enter לשליחה)",
    chatEmpty: "כתוב מה לשנות בתסריט...",
    // Shot list tab
    shotListTitle: "שוט ליסט",
    shotsCount: "שוטים",
    filter: "סינון",
    view: "תצוגה",
    addShot: "שוט",
    addShotFull: "הוסף שוט",
    addFirstShot: "הוסף שוט ראשון",
    noShotsYet: "אין שוטים עדיין",
    emptyShotListHint: 'לחץ "הוסף שוט" להתחיל לבנות את השוט ליסט',
    moreShots: "עוד שוטים",
    shotLimit: "מגבלת",
    shotLimitSuffix: "שוטים",
    upgradeToPro: "שדרג ל-Pro",
    // Upgrade features
    cinematicFeature: 'תצוגה "קולנועי"',
    callSheetFeature: "קול שיט",
    storyboardShotsFeature: "שוטים בסטורי בורד",
  },

  // Call sheet
  callSheet: {
    title: "קול שיט",
    exporting: "מייצא...",
    exportPDF: "ייצוא PDF",
    light: "בהיר",
    dark: "כהה",
    projectLabel: "פרויקט:",
    clientLabel: "לקוח:",
    platformLabel: "פלטפורמה:",
    dateLabel: "תאריך",
    shotsCount: "שוטים",
    castSection: "הרכב שחקנים",
    lensSection: "עדשות",
    scheduleSection: "לו״ז צילומים",
    noShotsAdded: "לא נוספו שוטים לשוט ליסט",
    sceneName: "שם סצנה",
    movement: "תנועה",
    lens: "עדשה",
    fps: "FPS",
    audio: "אודיו",
    actor: "שחקן",
    actionDesc: "אקשן / תיאור",
    producedBy: 'הופק ע"י Planify',
  },

  // Financials extra
  financialExtra: {
    editInvoice: "עריכת חשבונית",
    newInvoice: "חשבונית חדשה",
    editInvoiceDetails: "ערוך את פרטי החשבונית",
    newInvoiceDetails: "הוסף חשבונית/הכנסה חדשה למערכת",
    selectClient: "בחר לקוח",
    selectProjectOptional: "בחר פרויקט (אופציונלי)",
    amountBeforeVat: 'סכום לפני מע"מ (₪)',
    dueDate: "תאריך יעד",
    externalInvoiceLink: "קישור לחשבונית חיצונית",
    updateInvoice: "עדכון חשבונית",
    addInvoice: "הוספת חשבונית",
    editExpense: "עריכת הוצאה",
    newExpense: "הוצאה חדשה",
    editExpenseDetails: "ערוך את פרטי ההוצאה",
    newExpenseDetails: "הוסף הוצאה חדשה למערכת",
    amount: "סכום (₪)",
    vendor: "ספק",
    attachReceipt: "צרף קבלה / PDF",
    clickToAttach: "לחץ לצירוף קובץ (PDF, JPG, PNG)",
    updateExpense: "עדכון הוצאה",
    addExpense: "הוספת הוצאה",
    editEquipment: "עריכת ציוד",
    newEquipment: "הוספת ציוד חדש",
    purchasePriceLabel: "מחיר רכישה (₪)",
  },

  // Financials page (table headers, stat cards, actions)
  financialPage: {
    uploadDocument: "העלאת מסמך",
    prevMonth: "חודש קודם",
    nextMonth: "חודש הבא",
    selectMonth: "בחר חודש",
    dateFilter: "סינון תאריכים",
    fromDate: "מתאריך",
    toDate: "עד תאריך",
    clearFilter: "נקה סינון",
    revenuePaid: "הכנסות (שולם)",
    openInvoices: "חשבוניות פתוחות",
    expenses: "הוצאות",
    profitLoss: "סך הכל רווח והפסד",
    fixedExpenses: "הוצאות קבועות",
    number: "מספר",
    dueDate: "תאריך יעד",
    validUntil: "בתוקף עד",
    viewInvoice: "צפייה בחשבונית",
    changeStatus: "שינוי סטטוס",
    current: "(נוכחי)",
    editAction: "עריכה",
    deleteAction: "מחיקה",
    monthNames: [
      "ינואר", "פברואר", "מרץ", "אפריל", "מאי", "יוני",
      "יולי", "אוגוסט", "ספטמבר", "אוקטובר", "נובמבר", "דצמבר",
    ],
    manageFixedExpenses: "ניהול הוצאות קבועות ←",
    serviceName: "שם השירות",
    cycle: "מחזור",
    monthlyCost: "עלות חודשית",
    nextBilling: "חיוב הבא",
    perYear: "/שנה",
    noFixedExpenses: "אין הוצאות קבועות",
  },

  // Document upload dialog
  docUpload: {
    scanTitle: "סריקת מסמך עם AI",
    scanDesc: "העלה חשבונית או קבלה — ה-AI יסרוק ויחלץ את הנתונים אוטומטית",
    dragOrClick: "גרור קובץ לכאן, או לחץ להעלאה",
    allowedFormats: "PDF · JPG · JPEG · PNG בלבד",
    aiVisionLabel: "AI Vision סורק חשבוניות בעברית",
    scanning: "סורק עם AI Vision...",
    identifyingFields: "מזהה סוג, סכום, ספק ותאריך",
    pleaseWait: "אנא המתן",
    invalidDocTitle: "נא להעלות מסמך חשבונאי בלבד",
    invalidDocDesc: "המסמך שהועלה אינו חשבונית, קבלה, או מסמך פיננסי",
    tryAgain: "נסה שוב",
    scannedSuccess: "הנתונים נסרקו בהצלחה",
    income: "הכנסה",
    expense: "הוצאה",
    docType: "סוג מסמך",
    expenseType: "הוצאה",
    invoiceType: "חשבונית / הכנסה",
    amountLabel: "סכום (₪)",
    clientOptional: "לקוח (אופציונלי)",
    noClient: "ללא לקוח",
    categoryLabel: "קטגוריה",
    vendorLabel: "ספק",
    savingLabel: "שומר...",
    saveExpense: "שמור הוצאה",
    saveInvoice: "שמור חשבונית",
    fileOnlyError: "ניתן להעלות קבצי PDF, JPG, JPEG, PNG בלבד",
    parseError: "שגיאה בניתוח המסמך",
    scanError: "שגיאה בסריקה",
    saveError: "שגיאה בשמירה",
  },

  // Calendar page extra
  calendarPage: {
    selectClient: "בחר לקוח",
    addToGCal: "הוסף לגוגל קלנדר",
    selectEventForGCal: "בחר אירוע להוספה לגוגל קלנדר",
    noEventsInView: "אין אירועים בתצוגה הנוכחית",
    exportLabel: "ייצוא",
    newShort: "חדש",
    clientPrefix: "לקוח",
  },

  // Calendar export extra (platform labels)
  calendarExportExtra: {
    platformShoot: "צילום",
    platformYouTube: "YouTube",
    platformReel: "Reel",
  },

  // Inspiration extras
  inspirationExtra: {
    editInspiration: "עריכת השראה",
    editDetails: "ערוך את פרטי ההשראה",
    addToBoard: "הוסף השראה חדשה ללוח",
    titleRequired: "כותרת *",
    linkLabel: "קישור",
    categoryRequired: "קטגוריה *",
    noCategoriesYet: "אין קטגוריות עדיין — סגור ולחץ על \"קטגוריות\" כדי ליצור אחת",
    selectCategory: "בחר קטגוריה",
    needCategoryFirst: "יש ליצור קטגוריה לפחות אחת לפני שמירה",
    saveError: "שגיאה בשמירה",
    openLink: "פתח קישור",
    categoriesBtn: "קטגוריות",
    inspirationRefs: "רפרנסים בהשראה",
    manageCategories: "ניהול קטגוריות",
    manageCategoriesDesc: "הוסף, ערוך או מחק קטגוריות השראה",
    noCategoriesEmpty: "אין קטגוריות עדיין. הוסף אחת למטה.",
    newCategory: "קטגוריה חדשה",
    categoryNamePlaceholder: "שם הקטגוריה...",
    createError: "שגיאה ביצירת קטגוריה",
    updateError: "שגיאה בעדכון קטגוריה",
    deleteError: "שגיאה במחיקת קטגוריה",
  },

  // Projects page extras
  projectsPage: {
    addToGCal: "הוסף ל-Google Calendar",
    createDriveFolder: "צור תיקיית Drive",
    noClientLabel: "ללא לקוח",
    driveSetupRequired: "חיבור Google Drive דורש הגדרה.",
    driveFolderError: "שגיאה ביצירת תיקייה",
  },

  // Contacts page extras
  contactsPage: {
    contactsFeature: "אנשי קשר",
  },

  // Subscriptions dialog extras
  subscriptionExtra: {
    editSubscription: "עריכת מנוי",
    editDetails: "ערוך את פרטי המנוי",
    addNew: "הוסף מנוי חדש למערכת",
    serviceName: "שם השירות",
    billingCycle: "מחזור חיוב",
    amountLabel: "סכום (₪)",
    nextBilling: "חיוב הבא",
  },

  // Travel dialog extras
  travelExtra: {
    editTrip: "עריכת נסיעה",
    editDetails: "ערוך את פרטי הנסיעה",
    addNew: "הוסף נסיעה חדשה ליומן",
    purposeLabel: "מטרה",
  },

  // Asset dialog extras
  assetExtra: {
    editAsset: "עריכת נכס",
    editDetails: "ערוך את פרטי הנכס",
    addNew: "הוסף נכס חדש לספרייה",
    nameRequired: "שם *",
    typeRequired: "סוג *",
    sourceLabel: "מקור",
    linkLabel: "קישור",
    openLabel: "פתח",
  },

  // Assets page extras
  assetsPage: {
    nameCol: "שם",
    typeCol: "סוג",
    sourceCol: "מקור",
    linkCol: "קישור",
    notesCol: "הערות",
    actionsCol: "פעולות",
  },

  // Quick links widget
  quickLinksExtra: {
    linkNamePlaceholder: "שם הקישור",
  },

  // Todo widget
  todoExtra: {
    dailyTasks: "משימות יומיות",
    limitReached: "מגבלת {limit} משימות — לחץ Enter לשדרוג",
  },

  // Leads Pipeline
  leads: {
    title: "לידים",
    newLead: "ליד חדש",
    editLead: "עריכת ליד",
    pipeline: "מעקב פניות",
    convertToClient: "הפוך ללקוח",
    converted: "הומר ללקוח בהצלחה",
    stages: {
      new: "ליד חדש",
      contacted: "נוצר קשר",
      qualified: "שיחה/פגישה",
      proposal_sent: "הצעת מחיר",
      won: "סגירה",
      lost: "אבוד",
    },
    sources: {
      instagram: "אינסטגרם",
      tiktok: "טיקטוק",
      facebook: "פייסבוק",
      referral: "הפניה",
      website: "אתר",
      linkedin: "לינקדאין",
      organic: "אורגני",
      other: "אחר",
    },
    serviceType: "סוג שירות",
    serviceTypePlaceholder: "לדוגמה: צילום, ניהול סושיאל...",
    source: "מקור",
    daysAgo: "ימים",
    addInteraction: "הוסף אינטראקציה",
    interactionTypes: {
      call: "שיחה",
      email: "אימייל",
      meeting: "פגישה",
      note: "הערה",
    },
    interactionSummary: "סיכום",
    noLeads: "אין לידים",
    noLeadsDesc: "הוסף ליד חדש כדי להתחיל",
    filterBySource: "סינון לפי מקור",
    allSources: "כל המקורות",
    analytics: {
      title: "ניתוח לידים",
      totalLeads: "סך לידים",
      newLeads: "לידים חדשים",
      closedWon: "נסגרו",
      lostLeads: "אבדו",
      conversionRate: "יחס המרה",
      pending: "ממתינים",
      trend: "לעומת החודש הקודם",
      leadsOverTime: "לידים לאורך זמן",
      byStage: "לפי שלב",
      bySource: "לפי מקור",
      closingsBySource: "סגירות לפי מקור",
      funnel: "משפך המרה",
      showAnalytics: "הצג ניתוח",
      hideAnalytics: "הסתר ניתוח",
    },
  },

  // Automations
  automations: {
    title: "אוטומציות",
    description: "הגדר תזכורות והתראות אוטומטיות",
    templates: {
      stale_lead_24h: { title: "ליד ללא מענה (24 שעות)", desc: "תזכורת כשליד לא קיבל מענה 24 שעות" },
      stale_lead_72h: { title: "ליד קר (3 ימים)", desc: "התראה כשליד לא קיבל מענה 3 ימים" },
      proposal_followup_3d: { title: "Follow-up הצעת מחיר (3 ימים)", desc: "תזכורת אם הצעת מחיר לא נענתה 3 ימים" },
      proposal_followup_7d: { title: "Follow-up הצעת מחיר (שבוע)", desc: "תזכורת נוספת אחרי שבוע" },
      deadline_24h: { title: "דדליין מתקרב", desc: "התראה 24 שעות לפני דדליין פרויקט" },
      overdue_invoice: { title: "חשבונית באיחור", desc: "התראה על חשבונית שלא שולמה" },
      task_reminder: { title: "משימות יומיות", desc: "תזכורת יומית על משימות פתוחות" },
    },
    enabled: "פעיל",
    disabled: "כבוי",
    categories: { leads: "לידים", proposals: "הצעות מחיר", projects: "פרויקטים", payments: "תשלומים", tasks: "משימות" },
  },

  // Notifications
  notifications: {
    title: "התראות",
    markAllRead: "סמן הכל כנקרא",
    noNotifications: "אין התראות",
    timeAgo: { now: "עכשיו", minutes: "דקות", hours: "שעות", days: "ימים" },
  },

  // Share
  share: {
    title: "שיתוף פרויקט",
    generateLink: "צור קישור שיתוף",
    copyLink: "העתק קישור",
    copied: "הקישור הועתק",
    allowDownload: "אפשר הורדה",
    expiryDate: "תאריך תפוגה",
    noteForClient: "הערה ללקוח",
    notePlaceholder: "הערה שתוצג ללקוח...",
    activeLinks: "קישורים פעילים",
    deactivate: "בטל",
    noExpiry: "ללא תפוגה",
    expired: "פג תוקף",
    poweredBy: "מופעל על ידי",
    projectStatus: "סטטוס הפרויקט",
    taskProgress: "התקדמות משימות",
    sharedBy: "שותף על ידי",
  },

  // Layout / meta
  meta: {
    description: "הכלי החכם לניהול ההפקות שלך — לקוחות, פרויקטים, תסריטים ולוחות תוכן במקום אחד.",
  },
} as const;
